import { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Eye, EyeOff } from 'lucide-react';
import { Button } from '@/src/components/ui/button';
import { Input } from '@/src/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/src/components/ui/card';
import { useAuth } from '@/src/components/auth/AuthContext';

export default function Login() { const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const params = new URLSearchParams(location.search); const [identifier, setIdentifier] = useState(''); const [password, setPassword] = useState(''); const [rememberMe, setRememberMe] = useState(false); const [show, setShow] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); const result = await login(identifier, password, rememberMe); if (result.success) navigate(params.get('returnTo') || '/account', { replace: true }); else setError(result.message || 'Invalid credentials'); setLoading(false); }; return <div className="container mx-auto px-4 py-20"><Card className="max-w-md mx-auto"><CardHeader><CardTitle className="text-2xl font-heading">Log in</CardTitle><CardDescription>Use your Terqivo email or username.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-5"><div className="space-y-2"><label className="text-sm font-medium">Email or Username</label><Input value={identifier} onChange={(e) => setIdentifier(e.target.value)} required autoComplete="username" /></div><div className="space-y-2"><label className="text-sm font-medium">Password</label><div className="relative"><Input value={password} onChange={(e) => setPassword(e.target.value)} type={show ? 'text' : 'password'} required autoComplete="current-password" className="pr-10" /><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-2.5 text-muted-foreground" aria-label="Toggle password visibility">{show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={rememberMe} onChange={(e) => setRememberMe(e.target.checked)} /> Remember me</label>{error && <p className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<Button className="w-full" disabled={loading}>{loading ? 'Signing in...' : 'Log in'}</Button><div className="flex justify-between text-sm"><Link className="text-primary hover:underline" to="/forgot-password">Forgot password?</Link><Link className="text-primary hover:underline" to={`/signup${location.search}`}>Create account</Link></div></form></CardContent></Card></div>; }
