import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/src/components/ui/button";
import { Input } from "@/src/components/ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/src/components/ui/card";

const maskEmail = (value: string) => { const [local, domain] = value.split("@"); return local && domain ? `${local.slice(0, 1)}${"*".repeat(Math.max(2, local.length - 1))}@${domain}` : value; };

export default function VerifyEmail() {
  const [params] = useSearchParams(); const location = useLocation(); const navigate = useNavigate(); const state = location.state as { email?: string; returnTo?: string } | null;
  const token = params.get("token") || ""; const [email, setEmail] = useState(state?.email || params.get("email") || ""); const [code, setCode] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [processingLink, setProcessingLink] = useState(Boolean(token)); const [processingCode, setProcessingCode] = useState(false); const [resending, setResending] = useState(false); const [countdown, setCountdown] = useState(0); const [verified, setVerified] = useState(false); const returnTo = state?.returnTo || params.get("returnTo") || "/account";
  useEffect(() => { if (!token) return; let cancelled = false; (async () => { try { const response = await fetch("/api/auth/verify-email-link", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token }) }); const result = await response.json(); if (cancelled) return; if (response.ok && result.success) { setVerified(true); setMessage(result.message || "Email verified successfully"); } else setError(result.message || "This verification link is invalid or expired"); } catch { if (!cancelled) setError("We could not verify this link. Please request a new one."); } finally { if (!cancelled) { setProcessingLink(false); const next = new URLSearchParams(); if (email) next.set("email", email); if (returnTo !== "/account") next.set("returnTo", returnTo); navigate({ pathname: "/verify-email", search: next.toString() }, { replace: true, state }); } } })(); return () => { cancelled = true; }; }, [token]);
  useEffect(() => { if (!countdown) return; const timer = window.setInterval(() => setCountdown((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [countdown]);
  const masked = useMemo(() => email ? maskEmail(email) : "your email address", [email]);
  const verifyCode = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setMessage(""); setProcessingCode(true); try { const response = await fetch("/api/auth/verify-email-code", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, code }) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || "The verification code is invalid or expired"); setVerified(true); setMessage(result.message || "Email verified successfully"); } catch (verificationError) { setError(verificationError instanceof Error ? verificationError.message : "The verification code is invalid or expired"); } finally { setProcessingCode(false); } };
  const resend = async () => { setError(""); setMessage(""); setResending(true); try { const response = await fetch("/api/auth/resend-verification", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "Please try again later"); setMessage("If this account is eligible, a new verification email has been requested."); setCountdown(60); setCode(""); } catch (resendError) { setError(resendError instanceof Error ? resendError.message : "Please try again later"); } finally { setResending(false); } };
  if (processingLink) return <div className="container mx-auto px-4 py-20 text-center"><h1 className="text-3xl font-heading font-bold mb-4">Verify your email</h1><p className="text-muted-foreground">Verifying your secure link...</p></div>;
  return <div className="container mx-auto px-4 py-20"><Card className="max-w-md mx-auto"><CardHeader><CardTitle className="text-2xl font-heading">{verified ? "Email verified successfully" : "Verify your email"}</CardTitle><CardDescription>{verified ? "Your Terqivo account is ready to use." : <>We sent a verification link and 6-digit code to <strong>{masked}</strong>. Either method can be used.</>}</CardDescription></CardHeader><CardContent className="space-y-5">{verified ? <Button className="w-full" onClick={() => navigate(returnTo, { replace: true })}>Continue to Account</Button> : <><form onSubmit={verifyCode} className="space-y-4"><div className="space-y-2"><label className="text-sm font-medium" htmlFor="verification-email">Email</label><Input id="verification-email" type="email" value={email} onChange={(event) => setEmail(event.target.value.toLowerCase())} required autoComplete="email" /></div><div className="space-y-2"><label className="text-sm font-medium" htmlFor="verification-code">6-digit verification code</label><Input id="verification-code" value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" placeholder="123456" required /></div>{error && <p className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{message && <p className="rounded-md bg-green-50 p-3 text-sm text-green-700">{message}</p>}<Button className="w-full" disabled={processingCode || code.length !== 6 || !email}>{processingCode ? "Verifying..." : "Verify Code"}</Button></form><Button variant="outline" className="w-full" disabled={resending || countdown > 0 || !email} onClick={() => void resend()}>{countdown ? `Resend available in ${countdown}s` : resending ? "Requesting..." : "Resend Code"}</Button><div className="flex justify-between text-sm"><Link className="text-primary hover:underline" to="/signup">Change email / Back to Signup</Link><Link className="text-primary hover:underline" to="/login">Log in</Link></div></>}</CardContent></Card></div>;
}
