import { useEffect, useState } from "react";
import { Plus, Pencil, Trash2 } from "lucide-react";
import { Button } from "@/src/components/ui/button";
import { Input } from "@/src/components/ui/input";
import { Card, CardContent } from "@/src/components/ui/card";
import { toast } from "sonner";

const empty = { name: "", code: "", symbol: "", prefix: "", suffix: "", isActive: true, isDefault: false, sortOrder: 0 };

export default function AdminCurrencies() {
  const [items, setItems] = useState<any[]>([]); const [form, setForm] = useState<any>(empty); const [editing, setEditing] = useState<string | null>(null);
  const load = async () => { const res = await fetch("/api/currencies"); const data = await res.json(); if (res.ok) setItems(data.data || []); else toast.error(data.message); };
  useEffect(() => { void load(); }, []);
  const change = (key: string, value: any) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); const res = await fetch(editing ? `/api/currencies/${editing}` : "/api/currencies", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, sortOrder: Number(form.sortOrder) || 0 }) }); const data = await res.json(); if (!res.ok) return toast.error(data.message); toast.success(editing ? "Currency updated" : "Currency added"); setForm(empty); setEditing(null); void load(); };
  const remove = async (id: string) => { if (!confirm("Delete this currency?")) return; const res = await fetch(`/api/currencies/${id}`, { method: "DELETE" }); const data = await res.json(); if (!res.ok) toast.error(data.message); else { toast.success("Currency deleted"); void load(); } };
  return <div className="space-y-6"><div><h2 className="text-3xl font-heading font-bold">Currencies</h2><p className="text-muted-foreground">Manage currencies used by courses.</p></div><Card><CardContent className="p-6"><form onSubmit={save} className="grid md:grid-cols-4 gap-3 items-end"><div><label className="text-sm">Name</label><Input value={form.name} onChange={(e) => change("name", e.target.value)} required /></div><div><label className="text-sm">Code</label><Input value={form.code} onChange={(e) => change("code", e.target.value.toUpperCase())} required /></div><div><label className="text-sm">Symbol</label><Input value={form.symbol} onChange={(e) => change("symbol", e.target.value)} placeholder="$" /></div><div><label className="text-sm">Prefix</label><Input value={form.prefix} onChange={(e) => change("prefix", e.target.value)} placeholder="Rs." /></div><div><label className="text-sm">Suffix</label><Input value={form.suffix} onChange={(e) => change("suffix", e.target.value)} placeholder="EUR" /></div><div><label className="text-sm">Sort order</label><Input type="number" value={form.sortOrder} onChange={(e) => change("sortOrder", e.target.value)} /></div><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={form.isActive} onChange={(e) => change("isActive", e.target.checked)} /> Active</label><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={form.isDefault} onChange={(e) => change("isDefault", e.target.checked)} /> Default</label><div className="md:col-span-4 flex gap-2"><Button type="submit">{editing ? <Pencil className="mr-2 h-4 w-4" /> : <Plus className="mr-2 h-4 w-4" />}{editing ? "Update currency" : "Add currency"}</Button>{editing && <Button type="button" variant="outline" onClick={() => { setEditing(null); setForm(empty); }}>Cancel</Button>}</div></form></CardContent></Card><Card><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/50 border-b"><tr><th className="p-4 text-left">Currency</th><th className="p-4 text-left">Display</th><th className="p-4 text-left">Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item._id} className="border-b"><td className="p-4">{item.name} ({item.code})</td><td className="p-4">{item.prefix || item.symbol} 1,000 {item.suffix}</td><td className="p-4">{item.isActive ? "Active" : "Inactive"}{item.isDefault ? " · Default" : ""}</td><td className="p-4 text-right"><Button variant="ghost" size="icon" onClick={() => { setEditing(item._id); setForm(item); }}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => remove(item._id)}><Trash2 className="h-4 w-4" /></Button></td></tr>)}</tbody></table></CardContent></Card></div>;
}
